import * as S from "./styles";
import Text from "../Utils/Text";
import Podium from "../Podium";
import { useState } from "react";
import { Button } from "../Button";
import Ranking from "../Ranking";
import { CountryDataProps } from "@src/types/types";

const MedalBoard = () => {
  const [seeAll, setSeeAll] = useState(false);
  const data: CountryDataProps[] = [
    {
      id: "CHN",
      name: "China",
      continent: "ASI",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/CHN.png",
      gold_medals: 21,
      silver_medals: 17,
      bronze_medals: 14,
      total_medals: 52,
      rank: 1,
      rank_total_medals: 2,
    },
    {
      id: "USA",
      name: "EUA",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/USA.png",
      gold_medals: 19,
      silver_medals: 29,
      bronze_medals: 27,
      total_medals: 75,
      rank: 2,
      rank_total_medals: 1,
    },
    {
      id: "FRA",
      name: "França",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/FRA.png",
      gold_medals: 12,
      silver_medals: 14,
      bronze_medals: 18,
      total_medals: 44,
      rank: 3,
      rank_total_medals: 3,
    },
    {
      id: "AUS",
      name: "Austrália",
      continent: "OCE",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/AUS.png",
      gold_medals: 12,
      silver_medals: 11,
      bronze_medals: 8,
      total_medals: 31,
      rank: 4,
      rank_total_medals: 5,
    },
    {
      id: "KOR",
      name: "República da Coréia",
      continent: "ASI",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/KOR.png",
      gold_medals: 11,
      silver_medals: 8,
      bronze_medals: 7,
      total_medals: 26,
      rank: 5,
      rank_total_medals: 6,
    },
    {
      id: "GBR",
      name: "Grã-Bretanha",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/GBR.png",
      gold_medals: 10,
      silver_medals: 12,
      bronze_medals: 16,
      total_medals: 38,
      rank: 6,
      rank_total_medals: 4,
    },
    {
      id: "JPN",
      name: "Japão",
      continent: "ASI",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/JPN.png",
      gold_medals: 10,
      silver_medals: 5,
      bronze_medals: 11,
      total_medals: 26,
      rank: 7,
      rank_total_medals: 6,
    },
    {
      id: "ITA",
      name: "Itália",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ITA.png",
      gold_medals: 9,
      silver_medals: 10,
      bronze_medals: 6,
      total_medals: 25,
      rank: 8,
      rank_total_medals: 8,
    },
    {
      id: "NED",
      name: "Países Baixos",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/NED.png",
      gold_medals: 6,
      silver_medals: 5,
      bronze_medals: 4,
      total_medals: 15,
      rank: 9,
      rank_total_medals: 10,
    },
    {
      id: "GER",
      name: "Alemanha",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/GER.png",
      gold_medals: 6,
      silver_medals: 5,
      bronze_medals: 2,
      total_medals: 13,
      rank: 10,
      rank_total_medals: 11,
    },
    {
      id: "CAN",
      name: "Canadá",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/CAN.png",
      gold_medals: 5,
      silver_medals: 4,
      bronze_medals: 8,
      total_medals: 17,
      rank: 11,
      rank_total_medals: 9,
    },
    {
      id: "HUN",
      name: "Hungria",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/HUN.png",
      gold_medals: 3,
      silver_medals: 3,
      bronze_medals: 2,
      total_medals: 8,
      rank: 12,
      rank_total_medals: 13,
    },
    {
      id: "ROU",
      name: "Romênia",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ROU.png",
      gold_medals: 3,
      silver_medals: 3,
      bronze_medals: 1,
      total_medals: 7,
      rank: 13,
      rank_total_medals: 15,
    },
    {
      id: "IRL",
      name: "Irlanda",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/IRL.png",
      gold_medals: 3,
      silver_medals: 0,
      bronze_medals: 3,
      total_medals: 6,
      rank: 14,
      rank_total_medals: 19,
    },
    {
      id: "BRA",
      name: "Brasil",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/BRA.png",
      gold_medals: 2,
      silver_medals: 4,
      bronze_medals: 5,
      total_medals: 11,
      rank: 15,
      rank_total_medals: 12,
    },
    {
      id: "NZL",
      name: "Nova Zelândia",
      continent: "OCE",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/NZL.png",
      gold_medals: 2,
      silver_medals: 4,
      bronze_medals: 1,
      total_medals: 7,
      rank: 16,
      rank_total_medals: 15,
    },
    {
      id: "SWE",
      name: "Suécia",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/SWE.png",
      gold_medals: 2,
      silver_medals: 3,
      bronze_medals: 2,
      total_medals: 7,
      rank: 17,
      rank_total_medals: 15,
    },
    {
      id: "UKR",
      name: "Ucrânia",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/UKR.png",
      gold_medals: 2,
      silver_medals: 2,
      bronze_medals: 3,
      total_medals: 7,
      rank: 18,
      rank_total_medals: 15,
    },
    {
      id: "CRO",
      name: "Croácia",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/CRO.png",
      gold_medals: 2,
      silver_medals: 1,
      bronze_medals: 1,
      total_medals: 4,
      rank: 19,
      rank_total_medals: 24,
    },
    {
      id: "BEL",
      name: "Bélgica",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/BEL.png",
      gold_medals: 2,
      silver_medals: 0,
      bronze_medals: 3,
      total_medals: 5,
      rank: 20,
      rank_total_medals: 22,
    },
    {
      id: "HKG",
      name: "Hong Kong, China",
      continent: "ASI",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/HKG.png",
      gold_medals: 2,
      silver_medals: 0,
      bronze_medals: 2,
      total_medals: 4,
      rank: 21,
      rank_total_medals: 24,
    },
    {
      id: "AZE",
      name: "Azerbaijão",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/AZE.png",
      gold_medals: 2,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 2,
      rank: 22,
      rank_total_medals: 37,
    },
    {
      id: "PHI",
      name: "Filipinas",
      continent: "ASI",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/PHI.png",
      gold_medals: 2,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 2,
      rank: 22,
      rank_total_medals: 37,
    },
    {
      id: "SRB",
      name: "Sérvia",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/SRB.png",
      gold_medals: 2,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 2,
      rank: 22,
      rank_total_medals: 37,
    },
    {
      id: "ISR",
      name: "Israel",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ISR.png",
      gold_medals: 1,
      silver_medals: 4,
      bronze_medals: 1,
      total_medals: 6,
      rank: 25,
      rank_total_medals: 19,
    },
    {
      id: "ESP",
      name: "Espanha",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ESP.png",
      gold_medals: 1,
      silver_medals: 2,
      bronze_medals: 5,
      total_medals: 8,
      rank: 26,
      rank_total_medals: 13,
    },
    {
      id: "GEO",
      name: "Geórgia",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/GEO.png",
      gold_medals: 1,
      silver_medals: 2,
      bronze_medals: 1,
      total_medals: 4,
      rank: 27,
      rank_total_medals: 24,
    },
    {
      id: "SUI",
      name: "Suíça",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/SUI.png",
      gold_medals: 1,
      silver_medals: 1,
      bronze_medals: 4,
      total_medals: 6,
      rank: 28,
      rank_total_medals: 19,
    },
    {
      id: "RSA",
      name: "África do Sul",
      continent: "AFR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/RSA.png",
      gold_medals: 1,
      silver_medals: 1,
      bronze_medals: 2,
      total_medals: 4,
      rank: 29,
      rank_total_medals: 24,
    },
    {
      id: "KAZ",
      name: "Cazaquistão",
      continent: "ASI",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/KAZ.png",
      gold_medals: 1,
      silver_medals: 1,
      bronze_medals: 2,
      total_medals: 4,
      rank: 29,
      rank_total_medals: 24,
    },
    {
      id: "TPE",
      name: "Chinese Taipei",
      continent: "ASI",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/TPE.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 3,
      total_medals: 4,
      rank: 31,
      rank_total_medals: 24,
    },
    {
      id: "UZB",
      name: "Uzbequistão",
      continent: "ASI",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/UZB.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 2,
      total_medals: 3,
      rank: 32,
      rank_total_medals: 31,
    },
    {
      id: "GUA",
      name: "Guatemala",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/GUA.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 1,
      total_medals: 2,
      rank: 33,
      rank_total_medals: 37,
    },
    {
      id: "CZE",
      name: "Tchéquia",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/CZE.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 1,
      total_medals: 2,
      rank: 33,
      rank_total_medals: 37,
    },
    {
      id: "ALG",
      name: "Argélia",
      continent: "AFR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ALG.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 1,
      rank: 35,
      rank_total_medals: 47,
    },
    {
      id: "ARG",
      name: "Argentina",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ARG.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 1,
      rank: 35,
      rank_total_medals: 47,
    },
    {
      id: "CHI",
      name: "Chile",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/CHI.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 1,
      rank: 35,
      rank_total_medals: 47,
    },
    {
      id: "DMA",
      name: "Dominica",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/DMA.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 1,
      rank: 35,
      rank_total_medals: 47,
    },
    {
      id: "ECU",
      name: "Equador",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ECU.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 1,
      rank: 35,
      rank_total_medals: 47,
    },
    {
      id: "SLO",
      name: "Eslovênia",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/SLO.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 1,
      rank: 35,
      rank_total_medals: 47,
    },
    {
      id: "NOR",
      name: "Noruega",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/NOR.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 1,
      rank: 35,
      rank_total_medals: 47,
    },
    {
      id: "LCA",
      name: "Santa Lúcia",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/LCA.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 1,
      rank: 35,
      rank_total_medals: 47,
    },
    {
      id: "UGA",
      name: "Uganda",
      continent: "AFR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/UGA.png",
      gold_medals: 1,
      silver_medals: 0,
      bronze_medals: 0,
      total_medals: 1,
      rank: 35,
      rank_total_medals: 47,
    },
    {
      id: "JAM",
      name: "Jamaica",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/JAM.png",
      gold_medals: 0,
      silver_medals: 2,
      bronze_medals: 1,
      total_medals: 3,
      rank: 44,
      rank_total_medals: 31,
    },
    {
      id: "MEX",
      name: "México",
      continent: "AME",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/MEX.png",
      gold_medals: 0,
      silver_medals: 2,
      bronze_medals: 1,
      total_medals: 3,
      rank: 44,
      rank_total_medals: 31,
    },
    {
      id: "PRK",
      name: "RPD da Coréia",
      continent: "ASI",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/PRK.png",
      gold_medals: 0,
      silver_medals: 2,
      bronze_medals: 1,
      total_medals: 3,
      rank: 44,
      rank_total_medals: 31,
    },
    {
      id: "GRE",
      name: "Grécia",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/GRE.png",
      gold_medals: 0,
      silver_medals: 1,
      bronze_medals: 4,
      total_medals: 5,
      rank: 47,
      rank_total_medals: 22,
    },
    {
      id: "POL",
      name: "Polônia",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/POL.png",
      gold_medals: 0,
      silver_medals: 1,
      bronze_medals: 3,
      total_medals: 4,
      rank: 48,
      rank_total_medals: 24,
    },
    {
      id: "KOS",
      name: "Kosovo",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/KOS.png",
      gold_medals: 0,
      silver_medals: 1,
      bronze_medals: 1,
      total_medals: 2,
      rank: 49,
      rank_total_medals: 37,
    },
    {
      id: "TUR",
      name: "Türkiye",
      continent: "EUR",
      flag_url:
        "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/TUR.png",
      gold_medals: 0,
      silver_medals: 1,
      bronze_medals: 1,
      total_medals: 2,
      rank: 49,
      rank_total_medals: 37,
    },
  ];

  return (
    <S.Board>
      <Text isTitle>Quadro de Medalhas</Text>
      <Podium data={data} />
      <Button.Root isLink action={() => setSeeAll(!seeAll)}>
        <Button.Text>{seeAll ? "Ver menos" : "Ver tudo"}</Button.Text>
      </Button.Root>
      {seeAll && <Ranking data={data}></Ranking>}
    </S.Board>
  );
};

export default MedalBoard;
