import { EventDataProps } from "@src/types/types";

export const validSports = [
  "Basketball",
  "Beach Volleyball",
  "Football",
  "Handball",
  "Table Tennis",
  "Judo",
  "Tennis",
  "Volleyball",
  "Water Polo",
];

export const sportsInPortuguese = [
  "Basquete",
  "Vôlei de Praia",
  "Futebol",
  "Handebol",
  "Tênis de Mesa",
  "Judô",
  "Tênis",
  "Vôlei",
  "Polo Aquático",
];


export const validCountries = [
  "China",
  "França",
  "Austrália",
  "EUA",
  "Grã-Bretanha",
  "Japão",
  "República da Coréia",
  "Itália",
  "Países Baixos",
  "Canadá",
  "Alemanha",
  "Hong Kong, China",
  "Croácia",
  "Azerbaijão",
  "Brasil",
  "Suécia",
  "Espanha",
  "África do Sul",
  "Argentina",
  "Equador",
  "Eslovênia",
  "Sérvia",
  "Israel",
  "México",
  "Grécia",
  "Polônia",
  "Ucrânia",
];

export const countriesInEnglish = [
  "China",
  "France",
  "Australia",
  "United States",
  "Great Britain",
  "Japan",
  "South Korea",
  "Italy",
  "Netherlands",
  "Canada",
  "Germany",
  "Hong Kong, China",
  "Croatia",
  "Azerbaijan",
  "Brazil",
  "Sweden",
  "Spain",
  "South Africa",
  "Argentina",
  "Ecuador",
  "Slovenia",
  "Serbia",
  "Israel",
  "Mexico",
  "Greece",
  "Poland",
  "Ukraine",
];

export const data: EventDataProps[] = [
  {
    id: 13625,
    day: "2024-07-24",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Geoffroy-Guichard Stadium",
    event_name: "Men",
    detailed_event_name: "Men's Group B",
    start_date: "2024-07-24T15:00:00+02:00",
    end_date: "2024-07-24T16:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "M",
    competitors: [
      {
        country_id: "Argentina",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ARG.png",
        competitor_name: "Messi",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "1",
      },
      {
        country_id: "Marrocos",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/MAR.png",
        competitor_name: "Hakimi",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "2",
      },
    ],
  },
  {
    id: 13626,
    day: "2024-07-24",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Parc des Princes",
    event_name: "Men",
    detailed_event_name: "Men's Group C",
    start_date: "2024-07-24T15:00:00+02:00",
    end_date: "2024-07-24T16:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "M",
    competitors: [
      {
        country_id: "Uzbequistão",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/UZB.png",
        competitor_name: "Uzbekistan",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "1",
      },
      {
        country_id: "Espanha",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ESP.png",
        competitor_name: "Gavi",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "2",
      },
    ],
  },
  {
    id: 13635,
    day: "2024-07-24",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Lyon Stadium",
    event_name: "Men",
    detailed_event_name: "Men's Group B",
    start_date: "2024-07-24T19:00:00+02:00",
    end_date: "2024-07-24T20:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "M",
    competitors: [
      {
        country_id: "Iraque",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/IRQ.png",
        competitor_name: "kkkkk",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "2",
      },
      {
        country_id: "Ucrânia",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/UKR.png",
        competitor_name: "traumatismo",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "1",
      },
    ],
  },
  {
    id: 13636,
    day: "2024-07-24",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Bordeaux Stadium",
    event_name: "Men",
    detailed_event_name: "Men's Group D",
    start_date: "2024-07-24T19:00:00+02:00",
    end_date: "2024-07-24T20:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "M",
    competitors: [
      {
        country_id: "Japão",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/JPN.png",
        competitor_name: "Japan",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "5",
      },
      {
        country_id: "Paraguai",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/PAR.png",
        competitor_name: "Paraguay",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "0",
      },
    ],
  },
  {
    id: 13641,
    day: "2024-07-24",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Marseille Stadium",
    event_name: "Men",
    detailed_event_name: "Men's Group A",
    start_date: "2024-07-24T21:00:00+02:00",
    end_date: "2024-07-24T22:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "M",
    competitors: [
      {
        country_id: "França",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/FRA.png",
        competitor_name: "France",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "3",
      },
      {
        country_id: "EUA",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/USA.png",
        competitor_name: "United States",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "0",
      },
    ],
  },
  {
    id: 13642,
    day: "2024-07-24",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Parc des Princes",
    event_name: "Men",
    detailed_event_name: "Men's Group D",
    start_date: "2024-07-24T21:00:00+02:00",
    end_date: "2024-07-24T22:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "M",
    competitors: [
      {
        country_id: "Mali",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/MLI.png",
        competitor_name: "Mali",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "T",
        result_mark: "1",
      },
      {
        country_id: "Israel",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ISR.png",
        competitor_name: "Israel",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "T",
        result_mark: "1",
      },
    ],
  },
  {
    id: 13645,
    day: "2024-07-25",
    discipline_name: "Handball",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/HBL.avif",
    name: null,
    venue_name: "South Paris Arena 6",
    event_name: "Women",
    detailed_event_name: "Women's Preliminary Round Group A",
    start_date: "2024-07-25T09:00:00+02:00",
    end_date: "2024-07-25T10:30:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "Eslovênia",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/SLO.png",
        competitor_name: "Slovenia",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "19",
      },
      {
        country_id: "Dinamarca",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/DEN.png",
        competitor_name: "Denmark",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "27",
      },
    ],
  },
  {
    id: 13647,
    day: "2024-07-25",
    discipline_name: "Handball",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/HBL.avif",
    name: null,
    venue_name: "South Paris Arena 6",
    event_name: "Women",
    detailed_event_name: "Women's Preliminary Round Group B",
    start_date: "2024-07-25T11:00:00+02:00",
    end_date: "2024-07-25T12:30:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "Países Baixos",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/NED.png",
        competitor_name: "Netherlands",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "34",
      },
      {
        country_id: "Angola",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ANG.png",
        competitor_name: "Angola",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "31",
      },
    ],
  },
  {
    id: 13648,
    day: "2024-07-25",
    discipline_name: "Handball",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/HBL.avif",
    name: null,
    venue_name: "South Paris Arena 6",
    event_name: "Women",
    detailed_event_name: "Women's Preliminary Round Group B",
    start_date: "2024-07-25T14:00:00+02:00",
    end_date: "2024-07-25T15:30:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "Espanha",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ESP.png",
        competitor_name: "gabi",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "18",
      },
      {
        country_id: "Brasil",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/BRA.png",
        competitor_name: "neymar",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "29",
      },
    ],
  },
  {
    id: 13654,
    day: "2024-07-25",
    discipline_name: "Handball",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/HBL.avif",
    name: null,
    venue_name: "South Paris Arena 6",
    event_name: "Women",
    detailed_event_name: "Women's Preliminary Round Group A",
    start_date: "2024-07-25T16:00:00+02:00",
    end_date: "2024-07-25T17:30:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "Alemanha",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/GER.png",
        competitor_name: "Neuer",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "22",
      },
      {
        country_id: "República da Coréia",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/KOR.png",
        competitor_name: "TESTE",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "23",
      },
    ],
  },
  {
    id: 13657,
    day: "2024-07-25",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Geoffroy-Guichard Stadium",
    event_name: "Women",
    detailed_event_name: "Women's Group A",
    start_date: "2024-07-25T17:00:00+02:00",
    end_date: "2024-07-25T18:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "Canadá",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/CAN.png",
        competitor_name: "Sei la tio",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "2",
      },
      {
        country_id: "Nova Zelândia",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/NZL.png",
        competitor_name: "Zelandio",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "1",
      },
    ],
  },
  {
    id: 13658,
    day: "2024-07-25",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "La Beaujoire Stadium",
    event_name: "Women",
    detailed_event_name: "Women's Group C",
    start_date: "2024-07-25T17:00:00+02:00",
    end_date: "2024-07-25T18:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "Espanha",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ESP.png",
        competitor_name: "Spain",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "2",
      },
      {
        country_id: "Japão",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/JPN.png",
        competitor_name: "Japan",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "1",
      },
    ],
  },
  {
    id: 13659,
    day: "2024-07-25",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Marseille Stadium",
    event_name: "Women",
    detailed_event_name: "Women's Group B",
    start_date: "2024-07-25T19:00:00+02:00",
    end_date: "2024-07-25T20:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "Alemanha",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/GER.png",
        competitor_name: "Germany",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "3",
      },
      {
        country_id: "Austrália",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/AUS.png",
        competitor_name: "Australia",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "0",
      },
    ],
  },
  {
    id: 13660,
    day: "2024-07-25",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Bordeaux Stadium",
    event_name: "Women",
    detailed_event_name: "Women's Group C",
    start_date: "2024-07-25T19:00:00+02:00",
    end_date: "2024-07-25T20:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "Nigéria",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/NGR.png",
        competitor_name: "Nigeria",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "0",
      },
      {
        country_id: "Brasil",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/BRA.png",
        competitor_name: "Brazil",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "1",
      },
    ],
  },
  {
    id: 13661,
    day: "2024-07-25",
    discipline_name: "Handball",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/HBL.avif",
    name: null,
    venue_name: "South Paris Arena 6",
    event_name: "Women",
    detailed_event_name: "Women's Preliminary Round Group B",
    start_date: "2024-07-25T19:00:00+02:00",
    end_date: "2024-07-25T20:30:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "Hungria",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/HUN.png",
        competitor_name: "Hungary",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "28",
      },
      {
        country_id: "França",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/FRA.png",
        competitor_name: "France",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "31",
      },
    ],
  },
  {
    id: 13664,
    day: "2024-07-25",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Lyon Stadium",
    event_name: "Women",
    detailed_event_name: "Women's Group A",
    start_date: "2024-07-25T21:00:00+02:00",
    end_date: "2024-07-25T22:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "França",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/FRA.png",
        competitor_name: "France",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "3",
      },
      {
        country_id: "Colômbia",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/COL.png",
        competitor_name: "Colombia",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "2",
      },
    ],
  },
  {
    id: 13665,
    day: "2024-07-25",
    discipline_name: "Football",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/FBL.avif",
    name: null,
    venue_name: "Nice Stadium",
    event_name: "Women",
    detailed_event_name: "Women's Group B",
    start_date: "2024-07-25T21:00:00+02:00",
    end_date: "2024-07-25T22:45:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "EUA",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/USA.png",
        competitor_name: "United States",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "3",
      },
      {
        country_id: "Zâmbia",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ZAM.png",
        competitor_name: "Zambia",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "0",
      },
    ],
  },
  {
    id: 13666,
    day: "2024-07-25",
    discipline_name: "Handball",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/HBL.avif",
    name: null,
    venue_name: "South Paris Arena 6",
    event_name: "Women",
    detailed_event_name: "Women's Preliminary Round Group A",
    start_date: "2024-07-25T21:00:00+02:00",
    end_date: "2024-07-25T22:30:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "W",
    competitors: [
      {
        country_id: "Noruega",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/NOR.png",
        competitor_name: "Norway",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "28",
      },
      {
        country_id: "Suécia",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/SWE.png",
        competitor_name: "Sweden",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "32",
      },
    ],
  },
  {
    id: 13678,
    day: "2024-07-27",
    discipline_name: "Handball",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/HBL.avif",
    name: null,
    venue_name: "South Paris Arena 6",
    event_name: "Men",
    detailed_event_name: "Men's Preliminary Round Group A",
    start_date: "2024-07-27T09:00:00+02:00",
    end_date: "2024-07-27T10:30:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "M",
    competitors: [
      {
        country_id: "Espanha",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/ESP.png",
        competitor_name: "Spain",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "25",
      },
      {
        country_id: "Eslovênia",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/SLO.png",
        competitor_name: "Slovenia",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "22",
      },
    ],
  },
  {
    id: 13681,
    day: "2024-07-27",
    discipline_name: "Volleyball",
    discipline_pictogram:
      "https://codante.s3.amazonaws.com/codante-apis/olympic-games/pictograms/VVO.avif",
    name: null,
    venue_name: "South Paris Arena 1",
    event_name: "Men",
    detailed_event_name: "Men's Preliminary Round - Pool C",
    start_date: "2024-07-27T09:00:00+02:00",
    end_date: "2024-07-27T10:30:00+02:00",
    status: "Finished",
    is_medal_event: 0,
    is_live: 0,
    gender_code: "M",
    competitors: [
      {
        country_id: "Japão",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/JPN.png",
        competitor_name: "Japan",
        position: 0,
        result_position: "",
        result_winnerLoserTie: "L",
        result_mark: "2",
      },
      {
        country_id: "Alemanha",
        country_flag_url:
          "https://codante.s3.amazonaws.com/codante-apis/olympic-games/flags/GER.png",
        competitor_name: "Germany",
        position: 1,
        result_position: "",
        result_winnerLoserTie: "W",
        result_mark: "3",
      },
    ],
  },
];
